export const REGISTER_CONTACT_REQUEST = "REGISTER_CONTACT_REQUEST";
export const REGISTER_CONTACT_SUCCESS = "REGISTER_CONTACT_SUCCESS";
export const REGISTER_CONTACT_FAIL = "REGISTER_CONTACT_FAIL";

export const ALL_CONTACT_REQUEST = "ALL_CONTACT_REQUEST";
export const ALL_CONTACT_SUCCESS = "ALL_CONTACT_SUCCESS";
export const ALL_CONTACT_FAIL = "ALL_CONTACT_FAIL";

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST";
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS";
export const DELETE_CONTACT_FAIL = "DELETE_CONTACT_FAIL";

export const EDIT_CONTACT_REQUEST = "EDIT_CONTACT_REQUEST";
export const EDIT_CONTACT_SUCCESS = "EDIT_CONTACT_SUCCESS";
export const EDIT_CONTACT_FAIL = "EDIT_CONTACT_FAIL";

export const CONTACT_DETAILS_REQUEST = "CONTACT_DETAILS_REQUEST";
export const CONTACT_DETAILS_SUCCESS = "CONTACT_DETAILS_SUCCESS";
export const CONTACT_DETAILS_FAIL = "CONTACT_DETAILS_FAIL";
